---

- name: Decommissioning all resouces
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    # First decommision the ec2 instance
    - name: Decommissioning the "{{ aws_ec2_name_tag }}" EC2 instance
      amazon.aws.ec2_instance:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent
        filters:
          instance-state-name: running
          "tag:Name": "{{ aws_ec2_name_tag }}"
          "tag:Environment": "{{ aws_ec2_env_tag }}"

    # Get VPC details to be able to remove it.
    - name: Get "{{ aws_vpc_name }}" VPC details
      register: vpc_info
      amazon.aws.ec2_vpc_net_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ aws_vpc_name }}"

    # Display vpc info
    - name: Output "{{ aws_vpc_name }}" info 
      debug:
        msg: "{{ vpc_info}}"

    # Decommissioning the internet gateway
    - name: Deleting the internet gateway in Environment
      loop: '{{ vpc_info.vpcs }}'
      community.aws.ec2_vpc_igw:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        vpc_id: "{{ item.vpc_id }}"
        state: absent

    # Decommissioning the routing table 
    - name: Decommissioning the "{{ aws_route_table_name }}" routing table 
      amazon.aws.ec2_vpc_route_table:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        tags:
          Name: "{{ aws_route_table_name }}"
        state: absent
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"

     # Listing VPC endpoints
    - name: Get endpoints for the "{{ aws_vpc_name }}" VPC
      register: ep_reg
      amazon.aws.ec2_vpc_endpoint_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"

    # Decommissioning Private Link endpoint
    - name: Delete the "{{ ep_reg.vpc_endpoints[0].vpc_endpoint_id }}" vpc endpoint
      amazon.aws.ec2_vpc_endpoint:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent
        vpc_endpoint_id: "{{ ep_reg.vpc_endpoints[0].vpc_endpoint_id }}"

    # Decommissioning the security groups
    - name: Gather information about all Security Groups in Environment
      register: sg_info
      amazon.aws.ec2_group_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"

    - name: Output aim_ansible_network security groups
      debug:
        msg: "{{ sg_info }}"

    - name: Delete Security Groups in VPC "{{ vpc_info.vpcs[0].vpc_id }}" by ID
      loop: "{{ sg_info.security_groups }}"
      when: item.group_name != "default"
      amazon.aws.ec2_group:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        group_id: "{{ item.group_id }}"
        state: absent

    # Decommission the subnet
    - name: Decommissioning the "{{ aws_vpc_subnet_name }}" subnet
      ec2_vpc_subnet:
        cidr: "{{ aws_subnet_cidr_block  }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        state: absent

    # Decommision the VPC
    - name: Decommissioning the "{{ aws_vpc_name }}" VPC
      amazon.aws.ec2_vpc_net:
        cidr_block: "{{ aws_vpc_cidr_block }}"
        name: "{{ aws_vpc_name }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent

    # Decomision the key-pair
    - name: remove key pair from AWS by name
      tags: 
        - rm_kp
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent

    # Delete aws key-pair form local dir
    - name: Remove file (delete file)
      tags:
        - rm_pem
      ansible.builtin.file:
        path: "{{ aws_wrk_dir }}/{{aws_key_name}}.pem"
        state: absent
