---

- name: Decommissioning all resouces
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    # First decommision the ec2 instance
    - name: Decommissioning the "{{ aws_ec2_name_tag }}" EC2 instance
      amazon.aws.ec2_instance:
        filters:
          instance-state-name: running
          "tag:Name": "{{ aws_ec2_name_tag }}"
          "tag:Environment": "{{ aws_ec2_env_tag }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent

    # Get VPC details to be able to remove it.
    - name: Get "{{ aws_vpc_name }}" VPC details
      register: vpc_info
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Name": "{{ aws_vpc_name }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"

    # Display vpc info
    - name: Output "{{ aws_vpc_name }}" info 
      debug:
        msg: "{{ vpc_info }}"

    # Decommissioning the internet gateway
    - name: Deleting the internet gateway in Environment
      community.aws.ec2_vpc_igw:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent
        vpc_id: "{{ item.vpc_id }}"
      loop: '{{ vpc_info.vpcs }}'

    # Decommissioning the routing table 
    - name: Decommissioning the "{{ aws_route_table_name }}" routing table 
      amazon.aws.ec2_vpc_route_table:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent
        tags:
          Name: "{{ aws_route_table_name }}"
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"

    # Decommissioning the security groups
    - name: Gather information about all Security Groups in Environment
      register: sg_info
      amazon.aws.ec2_group_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"

    - name: Output aim_ansible_network security groups
      debug:
        msg: "{{ sg_info }}"

    - name: Delete Security Groups in VPC "{{ vpc_info.vpcs[0].vpc_id }}" by ID
      amazon.aws.ec2_group:
        group_id: "{{ item.group_id }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent
      loop: "{{ sg_info.security_groups }}"
      when: item.group_name != "default"

    # Get subnets info for the VPC
    - name: Get subnets for the "{{ vpc_info.vpcs[0].id }}" VPC
      register: subnet_info
      amazon.aws.ec2_vpc_subnet_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
  
    # Decommission the subnet
    - name: Decommissioning the "{{ aws_vpc_subnet_name }}" subnet
      with_items: "{{ subnet_info.subnets }}"
      ec2_vpc_subnet:
        cidr: "{{ item.cidr_block }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        state: absent

    # Decommision the VPC
    - name: Decommissioning the "{{ aws_vpc_name }}" VPC
      amazon.aws.ec2_vpc_net:
        cidr_block: "{{ aws_vpc_cidr_block }}"
        name: "{{ aws_vpc_name }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent

    # Decomision the key-pair
    - name: remove key pair from AWS by name
      amazon.aws.ec2_key:
        name: "{{ aws_key_name }}"
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        state: absent
      tags: 
        - rm_kp

    # Delete aws key-pair form local dir
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: "{{ aws_wrk_dir }}/{{aws_key_name}}.pem"
        state: absent
      tags:
        - rm_kp_pem
