---

- name: test aws
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:

    - name: Grab VPC details
      amazon.aws.ec2_instance_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ aws_ec2_name_tag }}"
          instance-state-name: ["running"]
      register: ec2_node_info

    - name: Set ec2 facts
      set_fact:
         ips: "{{ ips|default([]) +
                 [ {  'PrivateIP': item.private_ip_address
                     ,'PublicIP':  item.public_ip_address
                     ,'Instance Type': item.instance_type
                     ,'Subnet': item.subnet_id
                 } ]
                                    }}"
      with_items: "{{ ec2_node_info.instances }}"

    - name: Display subnets fact
      debug:
        msg:
          - "{{ ips }}"


