---

- name: test aws
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:

    - name: Grab VPC details
      amazon.aws.ec2_vpc_net_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
            "tag:Name": "{{ aws_vpc_name }}"
      register: vpc_reg

    - name: Get subnets for the "{{ vpc_reg.vpcs[0].id }}" VPC
      amazon.aws.ec2_vpc_subnet_info:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_reg.vpcs[0].id }}"
      register: subnet_reg

    - name: Set fact subnets
      set_fact:
         subnets: "{{ subnets|default([]) + [ {'subnet_id': item.id} ] }}"
      with_items: "{{ subnet_reg.subnets }}"

    - name: Display subnets fact
      debug:
        msg: "{{ subnets[0].subnet_id }}"
      with_items: "{{ subnets }}"

