---

#################################################################
# Install CRDB

- name: Cockroach database and other tools installation
  hosts: all
  gather_facts: true
  remote_user: ec2-user           # use the uid in the ssh public key file

  vars_files:
    - vars.yml

  tasks:

    - name: Upgrading all packages
      become: true 
      dnf:
        name: "*"
        state: latest
      tags:
        - upgrd_pks
  
    - name: Installing additional packages
      become: true 
      dnf:
        name:
          - wget
          - bzip2
          - python-pip
          - nodejs
          - haproxy
          - libpq-devel
          - libffi-devel
          - bzip2-devel
          - readline-devel
          - zlib-devel
          - sqlite-devel
          - python3-devel
          - curl
          - llvm
          - ncurses-devel
          - xz-devel
          - openssl-devel
#          - redhat-rpm-config
          - gcc
          - git
          - xz-devel
          - nginx
        state: latest
      tags:
        - add_pks

    - name: Installing the Development tools package group
      become: true
      ansible.builtin.dnf:
        name: '@Server with GUI'
        state: present
      tags:
        - inst_devtools


    - name: Downloading and Unarchiving the CRDB tar file 
      ansible.builtin.unarchive:
        src: "{{ crdb_dwnload_url }}{{crdb_version}}.tgz"
        dest: /tmp
        remote_src: yes

    - name: Creating a  directory for the CRDB libraries
      become: true 
      ansible.builtin.file:
        path: /usr/local/lib/cockroach
        state: directory
        mode: '0755'

    - name: Copying cockroach libraries to /usr/local/lib
      become: true 
      ansible.builtin.copy:
        src: "/tmp/{{ crdb_version }}/lib/"
        dest: /usr/local/lib/cockroach
        remote_src: yes

    - name: Coping cockroach binary to /usr/local/bin
      become: true 
      ansible.builtin.copy:
        src: "/tmp/{{ crdb_version }}/cockroach"
        dest: /usr/local/bin
        mode: '0755'
        remote_src: yes

    - name: Creating the "{{ crdb_grp }}" group
      become: true 
      ansible.builtin.group:
        name: "{{ crdb_grp }}"
        state: present
      tags:
        - crch_usr

    - name: Creating the "{{ crdb_uid }}" user
      become: true 
      ansible.builtin.user:
        group: "{{ crdb_grp }}"
        home: "{{ crdb_home }}"
        name: "{{ crdb_uid }}"
        password: "{{ crdb_pwd | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      tags:
        - crch_usr

    - name: Insert "Match User" configuration block in /etc/ssh/sshd_config
      become: true 
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        append_newline: true
        prepend_newline: true
        block: |
          Match User roachie
          PasswordAuthentication yes
      tags:
        - sshd_conf

    - name: Restart service sshd
      become: true 
      ansible.builtin.service:
        name: sshd.service 
        state: restarted
      tags:
        - restart_sshd

    - name: Creating the home directory for CRDB
      become: true 
      ansible.builtin.file:
        group: "{{ crdb_grp }}"
        mode: '0777'
        owner: "{{ crdb_uid }}"
        path: "{{ crdb_home }}"
        state: directory
      tags:
        - crdb_home_dir

    - name: Creating cockroach subdirs
      become: true 
      ansible.builtin.file:
        group: "{{ crdb_grp }}"
        mode: '0777'
        owner: "{{ crdb_uid }}"
        path: "{{ crdb_home }}/{{ item }}"
        state: directory
      loop: "{{ crdb_dirs }}"
      tags:
        - crdb_home_subdir

    - name: Copying SQL scripts
      become: true 
      ansible.builtin.copy:
        dest: "{{ crdb_home }}/sql"
        group: "{{ crdb_grp }}"
        owner: "{{ crdb_uid }}"
        src: "{{ item }}"                  # Can I change this to github repo?
        mode: '0755'
      with_fileglob: "{{ sql_scrpt_dir }}/*"
      tags:
        - sql_scrpts

    - name: Copying haproxy configurations
      become: true 
      ansible.builtin.copy:
        dest: "{{ crdb_home }}/haproxy"
        group: "{{ crdb_grp }}"
        owner: "{{ crdb_uid }}"
        src: "{{ item }}"                  # Can I change this to github repo?
        mode: '0755'
      with_fileglob: "{{ os_haproxy_dir }}/*"
      tags:
        - ha_cfg

    - name: Copying Shell scripts
      become: true 
      ansible.builtin.copy:
        dest: "{{ crdb_home }}/scripts"
        group: "{{ crdb_grp }}"
        owner: "{{ crdb_uid }}"
        src: "{{ item }}"                  # Can I change this to github repo?
        mode: '0755'
      with_fileglob: "{{ os_scrpt_dir }}/*"
      tags:
        - os_scrpts

    - name: Copying Flask app
      become: true 
      ansible.builtin.copy:
        dest: "{{ crdb_home }}/app/"
        group: "{{ crdb_grp }}"
        owner: "{{ crdb_uid }}"
        src: "{{ flask_dir }}/"                  # Can I change this to github repo?
        mode: '0755'
      tags:
        - flask_app

    - name: Copying all data files
      become: true 
      ansible.builtin.copy:
        dest: "{{ crdb_home }}/dump"
        group: "{{ crdb_grp }}"
        owner: "{{ crdb_uid }}"
        mode: '0755'
        src: "{{ item }}"
      with_fileglob: "{{ os_data_dir }}/*"
      tags:
        - move_data
    
    - name: Deleting CRDB installer content & directory
      become: true 
      ansible.builtin.file:
        path: "/tmp/{{ crdb_version }}"
        state: absent
      tags:
        - cleanupCRDB
