---

#################################################################
# Install CRDB

- name: Cockroach Database and other tools installation
  hosts: all
  gather_facts: true
  remote_user: ainfanzon           # use the uid in the ssh public key file

  vars_files:
    - vars.yml

  tasks:
  
#    - name: touch the authorized_keys file
#      file:
#        access_time: preserve
#        mode: 600
#        modification_time: preserve
#        path: /home/ainfanzon/.ssh/authorized_keys
#        state: touch
#
#     - name: Add SSH public key to authorized_keys
#       become: alex_infanzonmunoz
#       lineinfile:
#         insertafter: EOF
#         line: "{{ public_ssh_key }}"
#         path: /home/ainfanzon/.ssh/authorized_keys
#         state: present

    - name: Upgrading all OS packages
      become: true 
      dnf:
        name: "*"
        state: latest

    - name: Unarchive a CRDB tar file 
      ansible.builtin.unarchive:
        src: "{{ crdb_dwnload_url }}{{crdb_version}}.tgz"
        dest: /tmp
        remote_src: yes

    - name: Create a directory for the CRDB libraries
      become: true 
      ansible.builtin.file:
        path: /usr/local/lib/cockroach
        state: directory
        mode: '0755'

    - name: Copy cockroach libraries to /usr/local/lib
      become: true 
      ansible.builtin.copy:
        src: "/tmp/{{ crdb_version }}/lib/"
        dest: /usr/local/lib/cockroach
        remote_src: yes

    - name: Copy cockroach binary to /usr/local/bin
      become: true 
      ansible.builtin.copy:
        src: "/tmp/{{ crdb_version }}/cockroach"
        dest: /usr/local/bin
        mode: '0755'
        remote_src: yes

    - name: Create a data directory for the CRDB
      become: true 
      ansible.builtin.file:
        path: /home/cockroach
        state: directory
        mode: '0766'

################################################################
# Start CRDB
#
# cockroach start --insecure --listen-addr=10.0.1.2:26257 --advertise-addr=10.0.1.2:26257 --join=10.0.1.2:26257,10.0.1.3:26257,10.0.1.4:26257 --http-addr 10.0.1.2:8080 --store=/home/cockroach/cr_data_0 --background
#
#
# Set license key
#
# SET CLUSTER SETTING cluster.organization = 'Acme Company';
# SET CLUSTER SETTING enterprise.license = 'xxxxxxxxxxxx';
#
# SHOW CLUSTER SETTING cluster.organization;
# SHOW CLUSTER SETTING enterprise.license;
#
# $ cat cockroach.log | grep license
