---

- name: Test dictionaries
  hosts: localhost

  vars:
    regions: ['us-east1', 'europe-west4', 'asia-southeast1']
    gcp_regions:
      - region: us-east1
        zone:
          - us-east1-b
          - us-east1-c
          - us-east1-d
      - region: us-east4
        zone:
          - us-east4-c
          - us-east4-b
          - us-east4-a
      - region: us-central1
        zone:
          - us-central1-c
          - us-central1-a
          - us-central1-f
          - us-central1-b
      - region: us-west1
        zone:
          - us-west1-b
          - us-west1-c
          - us-west1-a
      - region: europe-west4
        zone:
          - europe-west4-a
          - europe-west4-b
          - europe-west4-c
      - region: europe-west1
        zone:
          - europe-west1-b
          - europe-west1-d
          - europe-west1-c
      - region: europe-west3
        zone:
          - europe-west3-c
          - europe-west3-a
          - europe-west3-b
      - region: europe-west2
        zone:
          - europe-west2-c
          - europe-west2-b
          - europe-west2-a
      - region: asia-east1
        zone:
          - asia-east1-b
          - asia-east1-a
          - asia-east1-c
      - region: asia-southeast1
        zone:
          - asia-southeast1-b
          - asia-southeast1-a
          - asia-southeast1-c
      - region: asia-northeast1
        zone:
          - asia-northeast1-b
          - asia-northeast1-c
          - asia-northeast1-a
      - region: asia-south1
        zone:
          - asia-south1-c
          - asia-south1-b
          - asia-south1-a
      - region: australia-southeast1
        zone:
          - australia-southeast1-b
          - australia-southeast1-c
          - australia-southeast1-a
      - region: southamerica-east1
        zone:
          - southamerica-east1-b
          - southamerica-east1-c
          - southamerica-east1-a
      - region: africa-south1
        zone:
          -  africa-south1-a
          -  africa-south1-b
          -  africa-south1-c
      - region: asia-east2
        zone:
          - asia-east2-a
          - asia-east2-b
          - asia-east2-c
      - region: asia-northeast2
        zone:
          - asia-northeast2-a
          - asia-northeast2-b
          - asia-northeast2-c
      - region: asia-northeast3
        zone:
          - asia-northeast3-a
          - asia-northeast3-b
          - asia-northeast3-c
      - region: asia-south2
        zone:
          - asia-south2-a
          - asia-south2-b
          - asia-south2-c
      - region: asia-southeast2
        zone:
          - asia-southeast2-a
          - asia-southeast2-b
          - asia-southeast2-c
      - region: australia-southeast2
        zone:
          - australia-southeast2-a
          - australia-southeast2-b
          - australia-southeast2-c
      - region: europe-central2
        zone:
          - europe-central2-a
          - europe-central2-b
          - europe-central2-c
      - region: europe-north1
        zone:
          - europe-north1-a
          - europe-north1-b
          - europe-north1-c
      - region: europe-southwest1
        zone:
          - europe-southwest1-a
          - europe-southwest1-b
          - europe-southwest1-c
      - region: europe-west10
        zone:
          - europe-west10-a
          - europe-west10-b
          - europe-west10-c
      - region: europe-west12
        zone:
          - europe-west12-a
          - europe-west12-b
          - europe-west12-c
      - region: europe-west6
        zone:
          - europe-west6-a
          - europe-west6-b
          - europe-west6-c
      - region: europe-west8
        zone:
          - europe-west8-a
          - europe-west8-b
          - europe-west8-c
      - region: europe-west9
        zone:
          - europe-west9-a
          - europe-west9-b
          - europe-west9-c
      - region: me-central1
        zone:
          - me-central1-a
          - me-central1-b
          - me-central1-c
      - region: me-central2
        zone:
          - me-central2-a
          - me-central2-b
          - me-central2-c
      - region: me-west1
        zone:
          - me-west1-a
          - me-west1-b
          - me-west1-c
      - region: northamerica-northeast1
        zone:
          - northamerica-northeast1-a
          - northamerica-northeast1-b
          - northamerica-northeast1-c
      - region: northamerica-northeast2
        zone:
          - northamerica-northeast2-a
          - northamerica-northeast2-b
          - northamerica-northeast2-c
      - region: southamerica-west1
        zone:
          - southamerica-west1-a
          - southamerica-west1-b
          - southamerica-west1-c
      - region: us-east5
        zone:
          - us-east5-a
          - us-east5-b
          - us-east5-c
      - region: us-south1
        zone:
          - us-south1-a
          - us-south1-b
          - us-south1-c
      - region: us-west2
        zone:
          - us-west2-a
          - us-west2-b
          - us-west2-c
      - region: us-west3
        zone:
          - us-west3-a
          - us-west3-b
          - us-west3-c
      - region: us-west4
        zone:
          - us-west4-a
          - us-west4-b
          - us-west4-c
  tasks: 
    - name: Print Version
      debug:
        #msg: "{{ gcp_regions.region[item] }}"
        #msg: "{{ gcp_regions.item.region }}"
        #msg: "{{ item }}"
        msg: "{{ item | selectattr('zone[1]') }}"
          #msg: "{{ item | selectattr('zone', '==', 1) }}"
      loop: "{{ regions }}"
