---

#################################################################
# Install CRDB

- name: Start CRDB Cluster
  hosts: all
  gather_facts: true
  remote_user: ainfanzon

  vars_files:
    - vars.yml

  tasks:

   # You can also use the 'cmd' parameter instead of free form format.
  - name: This command will change the working directory to somedir/
    ansible.builtin.shell:
      cmd: cockroach start --insecure --listen-addr=localhost:26257 --advertise-addr=10.0.1.2 --join=10.0.1.2:26257,10.0.1.3:26257,10.0.1.4:26257 --http-addr=localhost:8080 --store=/home/cockroach/cr_data_0 --background
      #
################################################################
# Start CRDB
#
# cockroach start --insecure --listen-addr=10.0.1.2:26257 --advertise-addr=10.0.1.2:26257 --join=10.0.1.2:26257,10.0.1.3:26257,10.0.1.4:26257 --http-addr 10.0.1.2:8080 --store=/home/cockroach/cr_data_0 --background
#
#
# Set license key
#
# SET CLUSTER SETTING cluster.organization = 'Acme Company';
# SET CLUSTER SETTING enterprise.license = 'xxxxxxxxxxxx';
#
# SHOW CLUSTER SETTING cluster.organization;
# SHOW CLUSTER SETTING enterprise.license;
#
# $ cat cockroach.log | grep license
